### ISSUE TITLE
ERROR - 'NoneType' object is not subscriptable ( Google Bard )

### ISSUE THREAD

**Issue by 11100010** [Simatwa/gpt-cli#20]
Suddenly, Google Bard doesn't work no more. Meanwhile, Chatgpt is still fine.

> ┌─[0000@GPT-CLI]─(02:37:41)
└──╼ ❯❯❯hola
ERROR - 'NoneType' object is not subscriptable

Anybody can help? Thank you very much~

**Comment by 11100010** [comment]
Upgrading GoogleBard to 1.4.0 version solved the problem, but it adds "INFO - HTTP Request" line before every answer
```
┌─[0000@GPT-CLI]─(16:07:00)
└──╼ ❯❯❯hello
INFO - HTTP Request: POST https://bard.google.com/_/BardChatUi/data/assistant.lamda.BardFrontendService/StreamGenerate?bl=boq_assistant-bard-web-server_20230620.14_p0&_reqid=608525&rt=c "HTTP/1.1 200 OK" - (30-Jun-2023 01:44:21)
Hello there! How can I help you today?
```

**Comment by Simatwa** [comment]
Thanks for that. 
Currently fixed. 🙏

**Comment by 11100010** [comment]
Bard Error again, please
> ┌─[0000@GPT-CLI]─(07:26:13)
└──╼ ❯❯❯Hallo
INFO - HTTP Request: POST https://bard.google.com/_/BardChatUi/data/assistant.lamda.BardFrontendService/StreamGenerate?bl=boq_assistant-bard-web-server_20230620.14_p0&_reqid=8032&rt=c "HTTP/1.1 401 Unauthorized" - (08-Jul-2023 07:41:55)
ERROR - list index out of range - (08-Jul-2023 07:41:55)
