### ISSUE TITLE
Request New Feature: Support Bing Chat?

### ISSUE THREAD

**Issue by 11100010** [Simatwa/gpt-cli#26]
Would you add Bing Chat feature?

*Side issue: Looks like Google makes it very hard to use Bard outside of its website. Bard dies frequently in gpt-cli. Must delete cookies and refresh with new ones to be able to use it.

**Comment by 11100010** [comment]
I think the problem of Bard can be solved with this solution:
First: Use https://github.com/barnardb/cookies to download all kind of cookies related to domain google.com, you will find out there are a lot of "__Secure_1PSID" cookies.
Then: Just try it out every "__Secure_1PSID" cookie available, there should be one works stably.

**Comment by Simatwa** [comment]
> Would you add Bing Chat feature?
> 
> *Side issue: Looks like Google makes it very hard to use Bard outside of its website. Bard dies frequently in gpt-cli. Must delete cookies and refresh with new ones to be able to use it.

Nice idea folk. I will consider this feature in the next releases.
