### ISSUE TITLE
Google changed the __Secure-1PSID value format already

### ISSUE THREAD

**Issue by 11100010** [Simatwa/gpt-cli#30]
Hi everyone,
Does anyone know a way to work around it?
> bard
╭───────────────── gpt-cli v1.5.8 ─────────────────╮
│                                                  │
│             Repo :                               │
│ https://github.com/Simatwa/gpt-cli               │
│             By   : Smartwa Caleb                 │
╰──────────────────────────────────────────────────╯
CRITICAL - __Secure-1PSID value must end with a single dot. Enter correct __Secure-1PSID value. - (18-Feb-2024 06:49:53)

**Comment by Simatwa** [comment]
I doubt if there's any. Otherwise, a fix is on the way featuring the new Gemini.
